import numpy as np

arr = np.random.randn(7)*5
print(arr)
print("")
print("abs is:")
print(np.abs(arr))
print("")
print("fabs is:")
print(np.fabs(arr))
print("")
print("sqrt is:")
print(np.sqrt(arr))
print("")
print("square is:")
print(np.square(arr))
print("")
print("exp is:")
print(np.exp(arr))
print("")
print("log is:")
print(np.log(arr))
print("")
print("log10 is:")
print(np.log10(arr))
print("")
print("log2 is:")
print(np.log2(arr))
print("")
print("log1p is:")
print(np.log1p(arr))
print("")
print("sign is:")
print(np.sign(arr))
print("")
print("ceil is:")
print(np.ceil(arr))
print("")
print("floor is:")
print(np.floor(arr))
print("")
print("rint is:")
print(np.rint(arr))
print("")
print("modf is:")
print(np.modf(arr))
print("")
print("isnan is:")
print(np.isnan(arr))
print("")
print("isfinite is:")
print(np.isfinite(arr))
print("")
print("isinf is:")
print(np.isinf(arr))
print("")
print("cos is:")
print(np.cos(arr))
print("")
print("cosh is:")
print(np.cosh(arr))
print("")
print("sin is:")
print(np.sin(arr))
print("")
print("sinh is:")
print(np.sinh(arr))
print("")
print("tan is:")
print(np.tan(arr))
print("")
print("tanh is:")
print(np.tanh(arr))
print("")
print("arccos is:")
print(np.arccos(arr))
print("")
print("arccosh is:")
print(np.arccosh(arr))
print("")
print("arcsin is:")
print(np.arcsin(arr))
print("")
print("arcsinh is:")
print(np.arcsinh(arr))
print("")
print("arctan is:")
print(np.arctan(arr))
print("")
print("arctanh is:")
print(np.arctanh(arr))
print("")
print("logical_not is:")
print(np.logical_not(arr))
