import numpy as np

arr = np.arange(-5,5,1)

print("")
print("add is:")
print(np.add(arr,arr))
print("")
print("subtract is:")
print(np.subtract(arr,arr))
print("")
print("multiply is:")
print(np.multiply(arr,arr))
print("")
print("divide is:")
print(np.divide(arr,arr))
print("")
print("floor_divide is:")
print(np.floor_divide(arr,arr))
print("")
print("power is:")
#print(np.power(arr,arr))
print("")
print("maximum is:")
print(np.maximum(arr,arr))
print("")
print("fmax is:")
print(np.fmax(arr,arr))
print("")
print("minimum is:")
print(np.minimum(arr,arr))
print("")
print("fmin is:")
print(np.fmin(arr,arr))
print("")
print("mod is:")
print(np.mod(arr,arr))
print("")
print("copysign is:")
print(np.copysign(arr,arr))
print("")
print("greater is:")
print(np.greater(arr,arr))
print("")
print("greater_equal is:")
print(np.greater_equal(arr,arr))
print("")
print("less is:")
print(np.less(arr,arr))
print("")
print("less_equal is:")
print(np.less_equal(arr,arr))
print("")
print("equal is:")
print(np.equal(arr,arr))
print("")
print("not_equal is:")
print(np.not_equal(arr,arr))
print("")
print("logical_and is:")
print(np.logical_and(arr,arr))
print("")
print("logical_or is:")
print(np.logical_or(arr,arr))
print("")
print("logical_xor is:")
print(np.logical_xor(arr,arr))
